accounts/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls import include, url
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm,
)




app_name='accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view, name="signup"),
    url(r'^login/$',views.login_view, name="login"),
    url(r'^logout/$',views.logout_view, name="logout"),
]

blog/urls.py
from django.conf.urls import include, url
from . import views 
from . import views as core_views
from django.urls import include, path
from django.views.generic import TemplateView
app_name ='blog'
urlpatterns = [
    url(r'^$', views.main,name='home'),
    url(r'^listaPersonajes$', views.listaPersonajes,name='personajes'),
    url(r'^signup$', views.signup,name='signup'),
    url(r'^tierList$', views.tierlist,name='tierlist'),
    url(r'^login/$',views.login_view, name="login"),
    url(r'^personajeFavorito$', views.personajeFavorito,name='personajeFavorito'),
    url(r'^post_detail$', views.post_detail,name='post_detail'),
    url(r'^post_new$', views.post_new,name='post_new'),
    url(r'^post_edit$', views.post_edit,name='post_edit'),
    



]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
]

mysite/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from rest_framework import routers
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.urls import path
from rest_framework import routers
from blog.quickstart import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)


urlpatterns = [
    url('admin/', admin.site.urls),
    url('', include('blog.urls')),
    url(r'personajes/', include('personajes.urls')),
    url(r'accounts/', include('accounts.urls')),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
    



]

personajes/urls.py
from django.conf.urls import include, url
from . import views
from django.urls import include, path
from django.views.generic import TemplateView

app_name ='personajes'
urlpatterns = [
    url(r'^corrin/$',views.corrin, name="corrin"),
    url(r'^cloud/$',views.cloud, name="cloud"),
    url(r'^ike/$',views.ike, name="ike"),
    url(r'^inkling/$',views.inkling, name="inkling"),
    url(r'^joker/$',views.joker, name="joker"),
    url(r'^lucina/$',views.lucina, name="lucina"),
    url(r'^marth/$',views.marth, name="marth"),
    url(r'^pit/$',views.pit, name="pit"),
    url(r'^roy/$',views.roy, name="roy"),
    url(r'^chrom/$',views.chrom, name="chrom"),
    url(r'^bayonetta/$',views.Bayonetta, name="Bayonetta"),
    url(r'^bowser/$',views.Bowser, name="Bowser"),
    url(r'^daisy/$',views.Daisy, name="Daisy"),
    url(r'^dark_samus/$',views.Dark_samus, name="Dark_samus"),
    url(r'^diddy_kong/$',views.Diddy_kong, name="Diddy_kong"),
    url(r'^donkey_kong/$',views.Donkey_kong, name="Donkey_kong"),
    url(r'^dr_mario/$',views.Dr_mario, name="Dr_mario"),
    url(r'^duck_hunt/$',views.Duck_hunt, name="Duck_hunt"),
    url(r'^falco/$',views.falco, name="falco"),
    url(r'^fox/$',views.fox, name="fox"),
    url(r'^ganondorf/$',views.ganondorf, name="ganondorf"),
    url(r'^greninja/$',views.greninja, name="greninja"),
    url(r'^hero/$',views.hero, name="hero"),
    url(r'^ice_climbers/$',views.ice_climbers, name="ice_climbers"),
    url(r'^/$',views.robin, name="robin"),
    url(r'^incineroar/$',views.incineroar, name="incineroar"),
    url(r'^isabelle/$',views.isabelle, name="isabelle"),
    url(r'^jigglypuff/$',views.jigglypuff, name="jigglypuff"),
    url(r'^ken/$',views.ken, name="ken"),
    url(r'^king_dedede/$',views.king_dedede, name="king_dedede"),
    url(r'^king_k_rool/$',views.king_k_rool, name="king_k_rool"),
    url(r'^kirby/$',views.kirby, name="kirby"),
    url(r'^little_mac/$',views.little_mac, name="little_mac"),
    url(r'^lucario/$',views.lucario, name="lucario"),
    url(r'^lucas/$',views.lucas, name="lucas"),
    url(r'^luigi/$',views.luigi, name="luigi"),
    url(r'^mario/$',views.mario, name="mario"),
    url(r'^mega_man/$',views.mega_man, name="mega_man"),
    url(r'^meta_knight/$',views.meta_knight, name="meta_knight"),
    url(r'^mewtwo/$',views.mewtwo, name="mewtwo"),
    url(r'^mr_game_and_watch/$',views.mr_game_and_watch, name="mr_game_and_watch"),
    url(r'^ness/$',views.ness, name="ness"),
    url(r'^olimar/$',views.olimar, name="olimar"),
    url(r'^pac_man/$',views.pac_man, name="pac_man"),
    url(r'^palutena/$',views.palutena, name="palutena"),
    url(r'^peach/$',views.peach, name="peach"),
    url(r'^pichu/$',views.pichu, name="pichu"),
    url(r'^pikachu/$',views.pikachu, name="pikachu"),
    url(r'^piranha_plant/$',views.piranha_plant, name="piranha_plant"),
    url(r'^pt_charizard/$',views.pt_charizard, name="pt_charizard"),
    url(r'^pt_ivysaur/$',views.pt_ivysaur, name="pt_ivysaur"),
    url(r'^pt_squirtle/$',views.pt_squirtle, name="pt_squirtle"),
    url(r'^richter/$',views.richter, name="richter"),
    url(r'^ridley/$',views.ridley, name="ridley"),
    url(r'^ryu/$',views.ryu, name="ryu"),
    url(r'^samus/$',views.samus, name="samus"),
    url(r'^simon/$',views.simon, name="simon"),
    url(r'^snake/$',views.snake, name="snake"),
    url(r'^sonic/$',views.sonic, name="sonic"),
    url(r'^terry/$',views.terry, name="terry"),
    url(r'^wolf/$',views.wolf, name="wolf"),
    url(r'^young_link/$',views.young_link, name="young_link"),
  



]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError


class CustomUserCreationForm(forms.Form):
    username = forms.CharField(label='Ingrese nombre de usuario', min_length=4, max_length=150)
    email = forms.EmailField(label='Ingrese email')
    password1 = forms.CharField(label='Ingrese password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirme password', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Nombre de usuario ya existes")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            
            raise  ValidationError("Email already exists")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")

        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user

accounts/views.py
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.shortcuts import HttpResponseRedirect
from .forms import CustomUserCreationForm
from django.contrib import messages

# Create your views here.


def signup_view(request):
    if request.method == 'POST':
        f = CustomUserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            return redirect('blog:home')
    else:
        f = CustomUserCreationForm()
    return render(request, 'accounts/signup.html', {'form': f})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in the user
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('blog:home')
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html',{'form':form })

def logout_view(request):
    logout(request)
    return HttpResponseRedirect("/accounts/login/")

accounts/templates/accounts/Index.html
<<<<<<< HEAD:blog/templates/blog/Index.html
 {% load static %}
<html>

<head>

    <link rel="stylesheet" href="{% static 'css/Portada.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script src="{% static 'js/jquery.flexslider.js' %}"></script>
=======
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/Portada.css" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script src="js/jquery.flexslider.js"></script>
>>>>>>> master:accounts/templates/accounts/Index.html
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<<<<<<< HEAD:blog/templates/blog/Index.html
    <script src="{% static 'js/modernizr.js' %}"></script>
    <script src="{% static 'js/jquery-2.2.4-min.js'%}"></script>



=======
    <script src="js/script.js"></script>
    <script src="js/modernizr.js"></script>
    <script src="js/jquery-2.2.4-min.js"></script>

    <script src="js/main-v1.1.js"></script>
>>>>>>> master:accounts/templates/accounts/Index.html

    </script>
    <title>La Biblioteca de Robin</title>
</head>

<<<<<<< HEAD:blog/templates/blog/Index.html

<title>Document</title>
</head>
<header>
    <div>
        <a>
            <h1 href="{% url 'blog:home' %}" class="Encabezado">Robin Resources</h1>
        </a>
    </div>

    <div id="cd-nav" class="">
        <a href="#0" class="cd-nav-trigger">Menu<span></span></a>
        <nav id="cd-main-nav">
            {% if user.is_authenticated %}
            <ul class="">
                <li><a href="{% url 'blog:personajes' %}">Lista de Personajes</a></li>
                <li><a href="TierList.html">Tier List</a></li>
                <li><a href="Glosario.html">Glosario</a></li>
                <li><a href="userPj.html">Tus Personajes</a></li>


            </ul>
            {% else %}
            <ul class="">
                <li><a href="{% url 'blog:personajes' %}">Lista de Personajes</a></li>
                <li><a href="TierList.html">Tier List</a></li>
                <li><a href="Glosario.html">Glosario</a></li>
                <li><a href="{% url 'accounts:signup' %}">REGÍSTRATE</a></li>


            </ul>
            {% endif %}

        </nav>
    </div>

=======
<header>
    <h1 class="Encabezado">Robin Resources</h1>
    <div id="cd-nav" class="">
        <a href="#0" class="cd-nav-trigger">Menu<span></span></a>

        <nav id="cd-main-nav">
            <ul class="">
                <li><a href="ListaPersonajes.html">Lista de Personajes</a></li>
                <li><a href="TierList.html">Tier List</a></li>
                <li><a href="Glosario.html">Glosario</a></li>

            </ul>
        </nav>
    </div>

    <div class="social-bar">
        <a href="https://discord.gg/yKGC4zD" class="fab fa-discord" target="_blank"></a>
        <a href="https://mail.google.com/mail/u/0/?tab=im#inbox?compose=DmwnWstqxHDbTxRcgMKbsdhlPkXltWxtxTTQgHqVRccSFZMzTGwzqhVkfkXQGqDNfjTfqWtwghmL" class="fab fa-google-plus-g" target="_blank"></a>
        <a href="https://www.twitter.com/" class="fab fa-twitter" target="_blank"></a>
    </div>


    </div>
>>>>>>> master:accounts/templates/accounts/Index.html
</header>

<body>

    <div class="slider col-sm-12">
        <div id="my-slider" class="carousel slide" data-ride="carousel">
            <!-- Botones de indicacion -->
            <ol class="carousel-indicators">
                <li data-target="#my-slider" data-slide-to="0" class="active"></li>
                <li data-target="#my-slider" data-slide-to="1"></li>
            </ol>

<<<<<<< HEAD:blog/templates/blog/Index.html

            <!--Contenido del Slider -->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <a href="Imagenes/chrom.jpg"><img class="Portrait" src="{% static 'Imagenes/marth.jpg' %}"></a>
                    <div class="carousel-caption centrarImagen">
                        <a href="{% url 'personajes:marth' %}">
=======
            <!--Contenido del Slider -->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <a href="Imagenes/chrom.jpg"><img class="Portrait" src="Personajes/imgPj/marth.jpg"></a>
                    <div class="carousel-caption centrarImagen">
                        <a href="Personajes/Marth.html">
>>>>>>> master:accounts/templates/accounts/Index.html
                            <h1 href="/Internet">Marth</h1>
                        </a>
                    </div>
                </div>
                <div class="item">
<<<<<<< HEAD:blog/templates/blog/Index.html
                    <img class="Portrait" src="{% static 'Imagenes/ike.jpg' %}">
                    <div class="carousel-caption">
                        <a href="{% url 'personajes:ike' %}">
=======
                    <img class="Portrait" src="Personajes/imgPj/ike.jpg">
                    <div class="carousel-caption">
                        <a href="Personajes/Ike.html">
>>>>>>> master:accounts/templates/accounts/Index.html
                            <h1 href="/Internet">Ike</h1>
                        </a>
                    </div>
                </div>
            </div>
            <!-- Control del silder-->
            <a class="left carousel-control" href="#my-slider" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Anterior</span>
            </a>
            <a class="right carousel-control" href="#my-slider" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Siguiente</span>
            </a>


        </div>
    </div>
    <div id="fondo" class="row start-lg middle-lg center-xs">
        <div class="col-xs-12 col-lg-6">
            <div class="box-prom">
                <div class="box-text">
                    Bienvenido
                </div>
<<<<<<< HEAD:blog/templates/blog/Index.html
                <img src="{% static 'Imagenes/chibi.jpeg' %}"> "Hola Soy Robin y te doy la bienvenida a mi biblioteca con informacion util "
=======
                <img src="Imagenes/chibi.jpeg"> "Hola Soy Robin y te doy la bienvenida a mi biblioteca con informacion util "
>>>>>>> master:accounts/templates/accounts/Index.html
            </div>
        </div>
        <div class="col-xs-12 col-lg-6">
            <div class="box-prom2">
                <div class="box-text">
<<<<<<< HEAD:blog/templates/blog/Index.html
                    <a>Aprenderas</a>
                </div>
                A ser mejor en el juegito de smash ultimate donde yo tambien participo :3
            </div>
        </div>
    </div>
    --
    <footer>
        <div id="footer-d" class="row start-lg middle-lg center-xs">
            <div class="col-xs-12 col-lg-12">
                <h1 class="Pie">Robin Resources</h1>
            </div>
        </div>
    </footer>
</body>
=======
                    <a>VALORACIONES</a>
                </div>
            </div>
        </div>
    </div>
</body>
--------------------------------------------------------------------
<footer>
    <div id="footer-d" class="row start-lg middle-lg center-xs">
        <div class="col-xs-12 col-lg-12">
            <h1 class="Pie">Robin Resources</h1>
        </div>
    </div>
</footer>
>>>>>>> master:accounts/templates/accounts/Index.html

</html>

accounts/templates/accounts/login.html
{% extends 'blog/base.html' %}{% block title %}Login{% endblock %} {% block content %}
<div style="text-align:center">
    <h2>Login</h2>
</div>
<div style="text-align:center">
    <form method="post" id="form_login">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</div>
<h3>Olvido la contraseña?</h3>
</a>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'blog/base.html' %} {% block content %}

<section id="main" class="wrapper">
    <div class="inner">
        <!-- Elements -->
        <h2 id="elements">Crea tu cuenta</h2>
        <div class="row 200% form-login">
            <div class="12u">

                <br>
                <form action="/accounts/signup/" method="POST" onsubmit="return enviar()">
                    {% csrf_token %} {{ form.as_p }}
                    <br>
                    <input type="submit" name="submit" value="Registrar">
                    <input type="button" name="back" value="Volver" onclick="location.href='/accounts/login'">


                </form>

            </div>
        </div>

    </div>
</section>

<script>
    function enviar() {
        alert("Cuenta creada con éxito.");
    }
</script>





{% endblock %}