accounts/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls import include, url
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm,
)




app_name='accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view, name="signup"),
    url(r'^login/$',views.login_view, name="login"),
    url(r'^logout/$',views.logout_view, name="logout"),
]

blog/urls.py
from django.conf.urls import include, url
from . import views 
from . import views as core_views
from django.urls import include, path
from django.views.generic import TemplateView
app_name ='blog'
urlpatterns = [
    url(r'^$', views.main,name='home'),
    url(r'^listaPersonajes$', views.listaPersonajes,name='personajes'),
    url(r'^signup$', views.signup,name='signup'),
    url(r'^tierList$', views.tierlist,name='tierlist'),
    url(r'^login/$',views.login_view, name="login"),
    url(r'^personajeFavorito$', views.personajeFavorito,name='personajeFavorito'),
    url(r'^post_detail$', views.post_detail,name='post_detail'),
    url(r'^post_new$', views.post_new,name='post_new'),
    url(r'^post_edit$', views.post_edit,name='post_edit'),
    



]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
]

mysite/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from rest_framework import routers
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.urls import path
from rest_framework import routers
from blog.quickstart import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)


urlpatterns = [
    url('admin/', admin.site.urls),
    url('', include('blog.urls')),
    url(r'personajes/', include('personajes.urls')),
    url(r'accounts/', include('accounts.urls')),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
    



]

personajes/urls.py
from django.conf.urls import include, url
from . import views
from django.urls import include, path
from django.views.generic import TemplateView

app_name ='personajes'
urlpatterns = [
    url(r'^corrin/$',views.corrin, name="corrin"),
    url(r'^cloud/$',views.cloud, name="cloud"),
    url(r'^ike/$',views.ike, name="ike"),
    url(r'^inkling/$',views.inkling, name="inkling"),
    url(r'^joker/$',views.joker, name="joker"),
    url(r'^lucina/$',views.lucina, name="lucina"),
    url(r'^marth/$',views.marth, name="marth"),
    url(r'^pit/$',views.pit, name="pit"),
    url(r'^roy/$',views.roy, name="roy"),
    url(r'^chrom/$',views.chrom, name="chrom"),
    url(r'^bayonetta/$',views.Bayonetta, name="Bayonetta"),
    url(r'^bowser/$',views.Bowser, name="Bowser"),
    url(r'^daisy/$',views.Daisy, name="Daisy"),
    url(r'^dark_samus/$',views.Dark_samus, name="Dark_samus"),
    url(r'^diddy_kong/$',views.Diddy_kong, name="Diddy_kong"),
    url(r'^donkey_kong/$',views.Donkey_kong, name="Donkey_kong"),
    url(r'^dr_mario/$',views.Dr_mario, name="Dr_mario"),
    url(r'^duck_hunt/$',views.Duck_hunt, name="Duck_hunt"),
    url(r'^falco/$',views.falco, name="falco"),
    url(r'^fox/$',views.fox, name="fox"),
    url(r'^ganondorf/$',views.ganondorf, name="ganondorf"),
    url(r'^greninja/$',views.greninja, name="greninja"),
    url(r'^hero/$',views.hero, name="hero"),
    url(r'^ice_climbers/$',views.ice_climbers, name="ice_climbers"),
    url(r'^/$',views.robin, name="robin"),
    url(r'^incineroar/$',views.incineroar, name="incineroar"),
    url(r'^isabelle/$',views.isabelle, name="isabelle"),
    url(r'^jigglypuff/$',views.jigglypuff, name="jigglypuff"),
    url(r'^ken/$',views.ken, name="ken"),
    url(r'^king_dedede/$',views.king_dedede, name="king_dedede"),
    url(r'^king_k_rool/$',views.king_k_rool, name="king_k_rool"),
    url(r'^kirby/$',views.kirby, name="kirby"),
    url(r'^little_mac/$',views.little_mac, name="little_mac"),
    url(r'^lucario/$',views.lucario, name="lucario"),
    url(r'^lucas/$',views.lucas, name="lucas"),
    url(r'^luigi/$',views.luigi, name="luigi"),
    url(r'^mario/$',views.mario, name="mario"),
    url(r'^mega_man/$',views.mega_man, name="mega_man"),
    url(r'^meta_knight/$',views.meta_knight, name="meta_knight"),
    url(r'^mewtwo/$',views.mewtwo, name="mewtwo"),
    url(r'^mr_game_and_watch/$',views.mr_game_and_watch, name="mr_game_and_watch"),
    url(r'^ness/$',views.ness, name="ness"),
    url(r'^olimar/$',views.olimar, name="olimar"),
    url(r'^pac_man/$',views.pac_man, name="pac_man"),
    url(r'^palutena/$',views.palutena, name="palutena"),
    url(r'^peach/$',views.peach, name="peach"),
    url(r'^pichu/$',views.pichu, name="pichu"),
    url(r'^pikachu/$',views.pikachu, name="pikachu"),
    url(r'^piranha_plant/$',views.piranha_plant, name="piranha_plant"),
    url(r'^pt_charizard/$',views.pt_charizard, name="pt_charizard"),
    url(r'^pt_ivysaur/$',views.pt_ivysaur, name="pt_ivysaur"),
    url(r'^pt_squirtle/$',views.pt_squirtle, name="pt_squirtle"),
    url(r'^richter/$',views.richter, name="richter"),
    url(r'^ridley/$',views.ridley, name="ridley"),
    url(r'^ryu/$',views.ryu, name="ryu"),
    url(r'^samus/$',views.samus, name="samus"),
    url(r'^simon/$',views.simon, name="simon"),
    url(r'^snake/$',views.snake, name="snake"),
    url(r'^sonic/$',views.sonic, name="sonic"),
    url(r'^terry/$',views.terry, name="terry"),
    url(r'^wolf/$',views.wolf, name="wolf"),
    url(r'^young_link/$',views.young_link, name="young_link"),
  



]

blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Personaje(models.Model):
    nombre = models.CharField(max_length=20) 
    foto = models.ImageField(upload_to="images", null=True, blank=True) 

    def __str__(self):
        return self.nombre
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    
    class Meta:
        permissions = (
            ('admin',_('Es administrador')),
            ('usuario',_('Es usuario')),
        )

blog/forms.py
from django import forms
from .models import Post,Personaje
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm





class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

class PersonajeForm(ModelForm):
    
    class Meta:
        model = Personaje
        fields = ['nombre','foto']
class CustomUserForm(UserCreationForm):    
    class Meta:
        model = User
        fields= ['first_name','last_name','email','username','password1','password2']

blog/quickstart/views.py
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from blog.quickstart.serializers import UserSerializer, GroupSerializer
from rest_framework.parsers import FileUploadParser
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status

class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
 
class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    

blog/views.py
from django.shortcuts import render
from django.utils import timezone
from django.views import generic
from .models import Post
from django.shortcuts import render, get_object_or_404,HttpResponseRedirect
from .forms import PostForm,PersonajeForm
from django.contrib.auth import login, authenticate,logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate





# Create your views here.

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in the user
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('blog:home')
    else:
        form = AuthenticationForm()

    return render(request, 'blog/login.html',{'form':form })
@login_required
def personajeFavorito(request):
    data = {
        'form':PersonajeForm()
    }
    
    if request.method == 'POST':
        form = PersonajeForm(request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            data['mensaje'] = "Personaje Agregado Correctamete"
    return render(request, 'blog/personajeFavorito.html', data)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect("/blog/login/")

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('')
    else:
        form = UserCreationForm()
    return render(request, 'blog/signup.html', {'form': form})




def main(request):
    return render(request, 'blog/Index.html')
def listaPersonajes (request):
    return render(request, 'blog/ListaPersonajes.html')
def tierlist (request):
        return render(request, 'blog/tiers.html')

def post_list(request):
    user = request.user
    if user.has_perm('blog.profesor'):
        posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
        return render(request, 'blog/post_list.html', {'posts': posts })
    else:
        return render(request, 'blog/home.html')
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': posts})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})
    
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

class personajesView(generic.ListView):
        template_name='blog/ListaPersonajes.html'
       

blog/templates/blog/ListaPersonajes.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/Portada.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>"Robin Resources"</title>
</head>
<header>

</header>
<ul class="">
    <li><a href="{% url 'blog:home' %}">Menu Principal</a></li>
</ul>

<body style='background: #333333'>
    <div class="social-bar">
        <a href="https://discord.gg/yKGC4zD" class="fab fa-discord" target="_blank"></a>
        <a href="https://mail.google.com/mail/u/0/?tab=im#inbox?compose=DmwnWstqxHDbTxRcgMKbsdhlPkXltWxtxTTQgHqVRccSFZMzTGwzqhVkfkXQGqDNfjTfqWtwghmL" class="fab fa-google-plus-g" target="_blank"></a>
        <a href="https://www.twitter.com/" class="fab fa-twitter" target="_blank"></a>
    </div>
    <div class="Encabezado">
        <h1>Selecciona tu personaje</h1>

    </div>
    <div id="listaPersonajes" class="NavegadorPersonajes">

        <div class="Cajapersonaje Joker">
            <a title="Joker" href="{% url 'personajes:joker' %}">Joker</a>
        </div>
        <div class="Cajapersonaje Ike">
            <a title="Ike" href="{% url 'personajes:ike' %}">Ike</a>
        </div>
        <div class="Cajapersonaje Corrin">
            <a title="Corrin" href="{% url 'personajes:corrin' %}">Corrin</a>
        </div>
        <div class="Cajapersonaje Cloud">
            <a title="Cloud" href="{% url 'personajes:cloud' %}">Cloud</a>
        </div>
        <div class="Cajapersonaje Robin">
            <a title="Robin" href="{% url 'personajes:robin' %}">Best Tactician Ever</a>
        </div>
        <div class="Cajapersonaje Marth">
            <a title="Marth" href="{% url 'personajes:marth' %}">Marth</a>
        </div>
        <div class="Cajapersonaje Link">
            <a title="Link" href="">Link</a>
        </div>
        <div class="Cajapersonaje Pit">
            <a title="Pit" href="{% url 'personajes:pit' %}">Pit Nigga</a>
        </div>
        <div class="Cajapersonaje Lucina">
            <a title="Lucina" href="{% url 'personajes:lucina' %}">Lucina</a>
        </div>
        <div class="Cajapersonaje Pulpo">
            <a title="Pulpo" href="{% url 'personajes:inkling' %}">Inkling</a>
        </div>
        <div class="Cajapersonaje Chrom">
            <a title="Chrom" href="{% url 'personajes:chrom' %}">Suegro del Tactician</a>
        </div>
        <div class="Cajapersonaje Roy">
            <a title="Roy" href="{% url 'personajes:roy' %}">Alt del Suegro</a>
        </div>
        <div class="Cajapersonaje Bayonetta">
            <a title="Bayonetta" href="{% url 'personajes:Bayonetta' %}">Bayonetta</a>
        </div>
        <div class="Cajapersonaje Bowser">
            <a title="Bowser" href="{% url 'personajes:Bowser' %}">Bowser</a>
        </div>
        <div class="Cajapersonaje Daisy">
            <a title="Daisy" href="{% url 'personajes:Daisy' %}">Daisy</a>
        </div>
        <div class="Cajapersonaje Dark_samus">
            <a title="Dark_samus" href="{% url 'personajes:Dark_samus' %}">Dark samus</a>
        </div>
        <div class="Cajapersonaje Diddy_kong">
            <a title="Diddy_kong" href="{% url 'personajes:Diddy_kong' %}">Diddy kong</a>
        </div>
        <div class="Cajapersonaje Donkey_kong">
            <a title="Donkey_kong" href="{% url 'personajes:Donkey_kong' %}">Donkey kong</a>
        </div>
        <div class="Cajapersonaje Dr_mario">
            <a title="Dr_mario" href="{% url 'personajes:Dr_mario' %}">Dr mario</a>
        </div>
        <div class="Cajapersonaje Duck_hunt">
            <a title="Duck_hunt" href="{% url 'personajes:Duck_hunt' %}">Duck Hunt</a>
        </div>
        <div class="Cajapersonaje falco">
            <a title="falco" href="{% url 'personajes:falco' %}">Falco</a>
        </div>
        <div class="Cajapersonaje fox">
            <a title="fox" href="{% url 'personajes:fox' %}">Fox</a>
        </div>
        <div class="Cajapersonaje ganondorf">
            <a title="ganondorf" href="{% url 'personajes:ganondorf' %}">Ganondorf</a>
        </div>
        <div class="Cajapersonaje greninja">
            <a title="greninja" href="{% url 'personajes:greninja' %}">Greninja</a>
        </div>
        <div class="Cajapersonaje hero">
            <a title="hero" href="{% url 'personajes:hero' %}">Hero</a>
        </div>
        <div class="Cajapersonaje ice_climbers">
            <a title="ice_climbers" href="{% url 'personajes:ice_climbers' %}">Ice climbers</a>
        </div>
        <div class="Cajapersonaje incineroar">
            <a title="incineroar" href="{% url 'personajes:incineroar' %}">Incineroar</a>
        </div>
        <div class="Cajapersonaje isabelle">
            <a title="isabelle" href="{% url 'personajes:isabelle' %}">isabelle</a>
        </div>
        <div class="Cajapersonaje jigglypuff">
            <a title="jigglypuff" href="{% url 'personajes:jigglypuff' %}">jigglypuff</a>
        </div>
        <div class="Cajapersonaje ken">
            <a title="ken" href="{% url 'personajes:ken' %}">Ken</a>
        </div>
        <div class="Cajapersonaje king_dedede">
            <a title="king_dedede" href="{% url 'personajes:king_dedede' %}">King Dedede</a>
        </div>
        <div class="Cajapersonaje king_k_rool">
            <a title="king_k_rool" href="{% url 'personajes:king_k_rool' %}">King K Rool</a>
        </div>
        <div class="Cajapersonaje kirby">
            <a title="kirby" href="{% url 'personajes:kirby' %}">Kirby</a>
        </div>
        <div class="Cajapersonaje little_mac">
            <a title="little_mac" href="{% url 'personajes:little_mac' %}">Little Mac</a>
        </div>
        <div class="Cajapersonaje lucario">
            <a title="lucario" href="{% url 'personajes:lucario' %}">Lucario</a>
        </div>
        <div class="Cajapersonaje lucas">
            <a title="lucas" href="{% url 'personajes:lucas' %}">Lucas</a>
        </div>
        <div class="Cajapersonaje luigi">
            <a title="luigi" href="{% url 'personajes:luigi' %}">Luigi</a>
        </div>
        <div class="Cajapersonaje mario">
            <a title="mario" href="{% url 'personajes:mario' %}">Mario</a>
        </div>
        <div class="Cajapersonaje mega_man">
            <a title="mega_man" href="{% url 'personajes:mega_man' %}">Mega Man</a>
        </div>
        <div class="Cajapersonaje meta_knight">
            <a title="meta_knight" href="{% url 'personajes:meta_knight' %}">Meta Knight</a>
        </div>
        <div class="Cajapersonaje mewtwo">
            <a title="mewtwo" href="{% url 'personajes:mewtwo' %}">Mewtwo</a>
        </div>
        <div class="Cajapersonaje mr_game_and_watch">
            <a title="mr_game_and_watch" href="{% url 'personajes:mr_game_and_watch' %}">Mr game and watch</a>
        </div>
        <div class="Cajapersonaje ness">
            <a title="ness" href="{% url 'personajes:ness' %}">Ness</a>
        </div>
        <div class="Cajapersonaje pac_man">
            <a title="pac_man" href="{% url 'personajes:pac_man' %}">Pac Man</a>
        </div>
        <div class="Cajapersonaje palutena">
            <a title="palutena" href="{% url 'personajes:palutena' %}">Palutena</a>
        </div>
        <div class="Cajapersonaje peach">
            <a title="peach" href="{% url 'personajes:peach' %}">Peach</a>
        </div>
        <div class="Cajapersonaje pichu">
            <a title="pichu" href="{% url 'personajes:pichu' %}">Pichu</a>
        </div>
        <div class="Cajapersonaje pikachu">
            <a title="pikachu" href="{% url 'personajes:pikachu' %}">Pikachu</a>
        </div>
        <div class="Cajapersonaje piranha_plant">
            <a title="piranha_plant" href="{% url 'personajes:piranha_plant' %}">Piranha Plant</a>
        </div>
        <div class="Cajapersonaje pt_charizard">
            <a title="pt_charizard" href="{% url 'personajes:pt_charizard' %}">Charizard</a>
        </div>
        <div class="Cajapersonaje pt_ivysaur">
            <a title="pt_ivysaur" href="{% url 'personajes:pt_ivysaur' %}">Ivysaur</a>
        </div>
        <div class="Cajapersonaje pt_squirtle">
            <a title="pt_squirtle" href="{% url 'personajes:pt_squirtle' %}">Squirtle</a>
        </div>
        <div class="Cajapersonaje richter">
            <a title="richter" href="{% url 'personajes:richter' %}">Richter</a>
        </div>
        <div class="Cajapersonaje ridley">
            <a title="ridley" href="{% url 'personajes:ridley' %}">Ridley</a>
        </div>
        <div class="Cajapersonaje ryu">
            <a title="ryu" href="{% url 'personajes:ryu' %}">Ryu</a>
        </div>
        <div class="Cajapersonaje samus">
            <a title="samus" href="{% url 'personajes:samus' %}">Samus</a>
        </div>
        <div class="Cajapersonaje simon">
            <a title="simon" href="{% url 'personajes:simon' %}">Simon</a>
        </div>
        <div class="Cajapersonaje snake">
            <a title="snake" href="{% url 'personajes:snake' %}">snake</a>
        </div>
        <div class="Cajapersonaje sonic">
            <a title="sonic" href="{% url 'personajes:sonic' %}">sonic</a>
        </div>
        <div class="Cajapersonaje terry">
            <a title="terry" href="{% url 'personajes:terry' %}">Terry</a>
        </div>
        <div class="Cajapersonaje wolf">
            <a title="wolf" href="{% url 'personajes:wolf' %}">wolf</a>
        </div>
        <div class="Cajapersonaje young_link">
            <a title="young_link" href="{% url 'personajes:young_link' %}">Young Link</a>
        </div>

        <style>
            html {
                background: #333;
            }
        </style>

</body>

</html>

blog/templates/blog/base.html
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script src="{% static 'js/jquery.flexslider.js' %}"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/Portada.css' %}">
<link rel="stylesheet" href="{% static 'style.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<script src="{% static 'js/modernizr.js' %}"></script>
<script src="{% static 'js/jquery-2.2.4-min.js'%}"></script>

<body>
    <div class="Encabezado">
        <h1>
            <a href="{% url 'blog:home' %}" class="Encabezado">Robin Resources</a>
        </h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                <div id="cd-nav" class="">
                    <a href="#0" class="cd-nav-trigger">Menu<span></span></a>
                    <nav id="cd-main-nav">
                        {% if user.is_authenticated %}
                        <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                        <ul class="">
                            <li><a href="{% url 'blog:personajes' %}">Lista de Personajes</a></li>
                            <li><a href="{% url 'blog:tierlist' %}">Tier List</a></li>
                            <li><a href="{% url 'blog:personajeFavorito' %}">Agregar Personaje Favorito</a></li>

                            <ul class="actions vertical">
                                <li>
                                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                                        Bienvenido : {{ request.user }}
                                        <br>
                                        <br>
                                        <button class="salir" type="submit">Cerrar Sesion</button>
                                    </form>

                                </li>
                            </ul>



                        </ul>
                        {% else %}
                        <ul class="">
                            <li><a href="{% url 'blog:personajes' %}">Lista de Personajes</a></li>
                            <li><a href="{% url 'blog:tierlist' %}">Tier List</a></li>
                            <li><a href="{% url 'blog:signup' %}">REGÍSTRATE</a></li>
                            <li><a href="{% url 'blog:login' %}">INICIAR SESION</a></li>


                        </ul>
                        {% endif %}
                    </nav>
                    <div class="social-bar">
                        <a href="https://discord.gg/yKGC4zD" class="fab fa-discord" target="_blank"></a>
                        <a href="https://mail.google.com/mail/u/0/?tab=im#inbox?compose=DmwnWstqxHDbTxRcgMKbsdhlPkXltWxtxTTQgHqVRccSFZMzTGwzqhVkfkXQGqDNfjTfqWtwghmL" class="fab fa-google-plus-g" target="_blank"></a>
                        <a href="https://www.twitter.com/" class="fab fa-twitter" target="_blank"></a>
                    </div>
                </div>

            </div>
        </div>
    </div>
    {% block content %} {% endblock %}
    <footer>
        <div id="footer-d" class="row start-lg middle-lg center-xs">
            <ul class="Pie">
                <h2>Contacto</h2>

                <li><span class="icon fa-envelope"></span> <a href="#">hans.arancibia@live.com</a></li>
            </ul>
        </div>

    </footer>
</body>

blog/templates/blog/login.html
{% extends 'blog/base.html' %}{% block title %}Login{% endblock %} {% block content %}
<div style="text-align:center">
    <h2>Login</h2>
</div>
<div style="text-align:center">
    <form method="post" id="form_login">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</div>

{% endblock %}

blog/templates/blog/personajeFavorito.html
{% extends 'blog/base.html' %} {% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit">Subir Imagen</button>
</form>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
       {% if user.is_authenticated %}
         <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %} {% block content %}
<h2>Sugerencias a los moderadores.</h2>
<form method="POST" class="post-form">{% csrf_token %} {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
 {% block content %}    
      {% for post in posts %}
        <div class="post">
            <div class="date">
                {{ post.published_date }}
            </div>
           <h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
 {% endblock %}